//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khachhang()
        {
            this.Donhangs = new HashSet<Donhang>();
            this.Giohangs = new HashSet<Giohang>();
        }
    
        public string Email { get; set; }
        public string Họ_tên { get; set; }
        public string SĐT { get; set; }
        public string Địa_chỉ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donhang> Donhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giohang> Giohangs { get; set; }
    }
}
public static bool capNhatKhachHang(int maKhachHang, int tienNo, int soXuTichLuy)
{
    MySqlConnection connection = DBConnect.getConnection();
    connection.Open();
    String sql = "Update KhachHang set TienNo=?TienNo, SoXuTichLuy=?SoXuTichLuy where MaKhachHang=?MaKhachHang";
    MySqlCommand cmd = new MySqlCommand(sql, connection);
    cmd.Parameters.AddWithValue("?TienNo", tienNo);
    cmd.Parameters.AddWithValue("?SoXuTichLuy", soXuTichLuy);
    cmd.Parameters.AddWithValue("?MaKhachHang", maKhachHang);
    cmd.ExecuteNonQuery();
    connection.Close();
    return true;
}